### ISSUE TITLE
Android 13 upgrade breaks screen cast

### ISSUE THREAD

**Issue by mcrownover** [shmykelsa/AAAD#207]
Samsung s22+.  Foreced update to Android 13.  Android Auto version 8.2.623924-release.  2022 Hyundai Elantra with Android Auto Wireless support. AAAD is still loading AA Mirror to the head unit.  However there is no screen cast.  I only get  the sidebar menu.

**Comment by songoku119** [comment]
Just seconding this.  Tried with multiple screen mirroring apps (AA Mirror, screen2auto,aastream) all with the same symptom. Fermata auto/carstream still functioning as expected.  I guess an update from developers might be needed

**Comment by drew6625** [comment]
Same issue as above, Samsung S22 Ultra in a 2023 Nissan Rogue. I have a  black screen when trying to use any of the apps listed including: Screen2Auto, AA Stream, and AA Mirror. Apps that work are Carstream and Fermata. Fermata will work for a little then a white screen appears and I can't use any of the functions.

I read in an Android Auto post the black screen mirroring issue may be due to the current version of Android Auto that was released and it happens with other applications.

**Comment by shmykelsa** [comment]
Closed. Please [see FAQs](https://github.com/shmykelsa/AAAD#i-have-a-problem-with-an-app-installed-by-aaad-could-you-help-me-out) for more information.
