### ISSUE TITLE
S2A Installation Failure: Signature Mismatch

### ISSUE THREAD

**Issue by optoluctor** [shmykelsa/AAAD#223]
After uninstalling Screen2Auto, I'm unable to reinstall using AAAD.
AAAD downloads and attempts installation but then fails with this error:
"Could not install app due to signature mismatch. The app was uninstalled without clearing its data."
I have manually searched for and removed all "ru.cvitnepei.neatruwtosceo" directories with root explorer, then uninstalled/reinstalled AAAD, but the error persists.
![image](https://user-images.githubusercontent.com/43626907/215532333-5ac0f448-6fcd-43c8-8522-9ed13f2ccd42.png)
![image](https://user-images.githubusercontent.com/43626907/215532388-37238f9a-f40c-41b1-a6df-f7547145901e.png)
Anyone have direction as to the directory(s) or file(s) needing deletion to enable reinstallation through AAAD?

**Comment by shmykelsa** [comment]
For starter, AAAD is really not suggested for rooted phones since [AA AIO TWEAKER](https://github.com/shmykelsa/AA-Tweaker) does a better job at patching the apps and it's more featured.

Nevertheless, a signature mismatch is often caused by already existing application being installed with a different signature so I'd advise first clearing any version of Screen2Auto currently installed.

Also, that does not look as the stock package manager. Are you running any 3rd party app installer? Are you running a custom ROM?

**Comment by optoluctor** [comment]
Thank you so much for the fast response! Your new version 5.2 AIO TWEAKER works wonderfully, I am now using it. (For some reason 5.0.2 stopped applying patches when I upgraded to Android 13.)
Also, you were exactly correct about the package manager. It's an alternative one, which attempts to sign standalone APK's to circumvent protection. I actually had to uninstall that manager to correct the issue!
