### ISSUE TITLE
AAAD don't work

### ISSUE THREAD

**Issue by PotroToro** [shmykelsa/AAAD#98]
I have android 11 and last version  AAAD PRO  and car application Subaru Startlink, but I don't see anything application in the car. What's happened?

**Comment by shmykelsa** [comment]
Please supply more informations such as:

- Android version
- Phone model
- Android Auto version
- AAAD version

**Comment by juv777** [comment]
*Android 11
* Samsung Note 10+
*Android Auto Version 6.5.612134
*AAAD version V 1.4 Pro version.

AA had to be updated by force as it was not connecting to Car.
Now, since updated to latest firmware - 6.6.612134, it is loosing
connection very frequently and giving me CONNECTION ERROR.

I am thinking a bug in the latest update??

**Comment by shmykelsa** [comment]
Duplicate of #92
